---
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: production
project-name: Thing Book
module-name:  Training
