---
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: threw,purchased,had,cought

---
spring:
  profiles: article
words: a,the,the

---
spring:
  profiles: adjective
words: beautiful,fabulous,fantastic,humongous

---
spring:
  profiles: noun
words: mobile,laptop,desktop,tabletPC

---
projectConfig:
  projectName: Thing Book
  moduleName: register manufacturer
